USE Hospitals
GO

/* 
	Вывод сведений о пространстве журнала для всех баз данных:
	В следующем примере выводятся сведения LOGSPACE для всех баз данных, содержащихся в экземпляре SQL Server.
	Transact-SQL 
*/

DBCC SQLPERF(LOGSPACE);  
GO  

SELECT * FROM dbo.hospital

-- пример с интернета про локальный, скалярные переменные
DECLARE @StartTime DateTime = SYSDATETIME()

WAITFOR DELAY '00:00:01'
DECLARE @Seconds int = DATEDIFF(Second, @StartTime,SYSDATETIME())
SELECT GETDATE(),'Обновление=Успех сек='+CAST(@Seconds AS VARCHAR(8)) -- пишем результат


USE Hospitals
GO

EXEC sp_MSdependencies '?'
GO

EXEC sp_MSdependencies @objname=N'dbo.doctor', @objtype=29, @flags=0x15000
GO

EXEC sp_MSdependencies N'dbo.region'

EXEC sp_MSdependencies N'dbo.patient'

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE='FOREIGN KEY'

SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE WHERE CONSTRAINT_NAME LIKE '%FK%'

SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE CONSTRAINT_NAME LIKE '%FK%' ORDER BY TABLE_NAME

SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS

SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE


SELECT CONSTRAINT_NAME, TABLE_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE='FOREIGN KEY'

SELECT CONSTRAINT_NAME, TABLE_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE='PRIMARY KEY'
GO

SELECT T.TABLE_NAME, TC.CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLES T
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC ON TC.TABLE_NAME=T.TABLE_NAME


IF OBJECT_ID ('get_dependencies', 'V') IS NOT NULL  
DROP VIEW get_dependencies;  
GO  

GO

CREATE VIEW get_dependencies
AS
SELECT 
	TC.TABLE_NAME AS [TABLEFROM],
	TCT.TABLE_NAME AS [TABLETO],
	CCU.COLUMN_NAME AS [FK]
FROM 
	INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC, 
	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TCT ON TCT.CONSTRAINT_NAME=RC.UNIQUE_CONSTRAINT_NAME, 
	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU
WHERE RC.CONSTRAINT_NAME=TC.CONSTRAINT_NAME AND TC.CONSTRAINT_NAME=CCU.CONSTRAINT_NAME
GO

SELECT * FROM get_dependencies


